SFB-72: start of custom codelist
lblod/frontend-form-builder pull request #84
Opened 2024-01-11 14:43 UTC by JonasVanHoof

## ID
 [SFB-72](https://binnenland.atlassian.net/browse/SFB-72)

 ## Description

The user wants to have a new interface where they want to see and edit code lists. The code lists that are generic may not be edited but the others can. I created a new page for showing the code lists and viewing them.

This is behind a feature flag so no one will notice this when it is off.

 ## Type of change

 - [ ] Bug fix
 - [x] New feature
 - [ ] Breaking change
 - [ ] Other

 ## How to test

1. Set the feature flag on false
2. Go to codelijsten in the ui
3. View all lists
4. See detail of a list go back

 ## Links to other PR's

 - /

2024-01-12 08:33 UTC, JonasVanHoof commented
@aatauil  Im not sure whats going wrong here. We have always had a tricky pagination when running the application locally but now when going to the next page it isn't even loading the other items. Also the sorting is doing strange.. the network tab shows a call for a symbolset from appuniversum instead of a new get call with a different page..
![image](https://github.com/lblod/frontend-form-builder/assets/36266973/9b78ad97-b2f2-45af-a5be-2e0ae1e7ec2d)

Can you have a look?

2024-01-17 11:02 UTC, ZijneDwaasheid requested changes

2024-01-17 11:02 UTC, ZijneDwaasheid commented on app/templates/codelijsten/index.hbs
> +      </AuTable>
also not scroll-able :)

2024-01-17 11:37 UTC, JonasVanHoof commented
@ZijneDwaasheid  Hm alright I see where this is going wrong haha. So I have this branch and then an extended one from this. The things you are saying are fixed in https://github.com/lblod/frontend-form-builder/pull/85. 

Sorry this makes it actually a little more difficult than I expected..  Maybe you should check https://github.com/lblod/frontend-form-builder/pull/85 as final product

2024-01-18 15:26 UTC, JonasVanHoof commented
Closing this branch as it is no more the base for the feature. The PR created of this branch is https://github.com/lblod/frontend-form-builder/pull/85 from now you can find latest here. Sorry for the big PR 🖖🏻

2024-01-18 15:26 UTC, closed without merging